config/routes.rb
Clogs::Engine.routes.draw do
  root to: 'clogs#index'
  resources :clogs
end

app/models/clogs/clog.rb
module Clogs
  class Clog < ActiveRecord::Base
    attr_accessible :controller, :db_runtime, :path, :status, :view_runtime
  end
end

app/controllers/clogs/application_controller.rb
module Clogs
  class ApplicationController < ActionController::Base
  end
end

app/controllers/clogs/clogs_controller.rb
require_dependency "clogs/application_controller"

module Clogs
  class ClogsController < ApplicationController
    # GET /clogs
    # GET /clogs.json
    def index
      @clogs = Clog.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @clogs }
      end
    end
  
    # GET /clogs/1
    # GET /clogs/1.json
    def show
      @clog = Clog.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @clog }
      end
    end
  
    # GET /clogs/new
    # GET /clogs/new.json
    def new
      @clog = Clog.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @clog }
      end
    end
  
    # GET /clogs/1/edit
    def edit
      @clog = Clog.find(params[:id])
    end
  
    # POST /clogs
    # POST /clogs.json
    def create
      @clog = Clog.new(params[:clog])
  
      respond_to do |format|
        if @clog.save
          format.html { redirect_to @clog, notice: 'Clog was successfully created.' }
          format.json { render json: @clog, status: :created, location: @clog }
        else
          format.html { render action: "new" }
          format.json { render json: @clog.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /clogs/1
    # PUT /clogs/1.json
    def update
      @clog = Clog.find(params[:id])
  
      respond_to do |format|
        if @clog.update_attributes(params[:clog])
          format.html { redirect_to @clog, notice: 'Clog was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @clog.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /clogs/1
    # DELETE /clogs/1.json
    def destroy
      @clog = Clog.find(params[:id])
      @clog.destroy
  
      respond_to do |format|
        format.html { redirect_to clogs_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/clogs/application_helper.rb
module Clogs
  module ApplicationHelper
  end
end

app/helpers/clogs/clogs_helper.rb
module Clogs
  module ClogsHelper
  end
end

app/views/clogs/clogs/_form.html.erb
<%= form_for(@clog) do |f| %>
  <% if @clog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clog.errors.count, "error") %> prohibited this clog from being saved:</h2>

      <ul>
      <% @clog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :controller %><br />
    <%= f.text_field :controller %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :view_runtime %><br />
    <%= f.text_field :view_runtime %>
  </div>
  <div class="field">
    <%= f.label :db_runtime %><br />
    <%= f.text_field :db_runtime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clogs/clogs/edit.html.erb
<h1>Editing clog</h1>

<%= render 'form' %>

<%= link_to 'Show', @clog %> |
<%= link_to 'Back', clogs_path %>

app/views/clogs/clogs/index.html.erb
<h1>Listing clogs</h1>

<table>
  <tr>
    <th>Controller</th>
    <th>Path</th>
    <th>Status</th>
    <th>View runtime</th>
    <th>Db runtime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clogs.each do |clog| %>
  <tr>
    <td><%= clog.controller %></td>
    <td><%= clog.path %></td>
    <td><%= clog.status %></td>
    <td><%= clog.view_runtime %></td>
    <td><%= clog.db_runtime %></td>
    <td><%= link_to 'Show', clog %></td>
    <td><%= link_to 'Edit', edit_clog_path(clog) %></td>
    <td><%= link_to 'Destroy', clog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clog', new_clog_path %>

app/views/clogs/clogs/new.html.erb
<h1>New clog</h1>

<%= render 'form' %>

<%= link_to 'Back', clogs_path %>

app/views/clogs/clogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Controller:</b>
  <%= @clog.controller %>
</p>

<p>
  <b>Path:</b>
  <%= @clog.path %>
</p>

<p>
  <b>Status:</b>
  <%= @clog.status %>
</p>

<p>
  <b>View runtime:</b>
  <%= @clog.view_runtime %>
</p>

<p>
  <b>Db runtime:</b>
  <%= @clog.db_runtime %>
</p>


<%= link_to 'Edit', edit_clog_path(@clog) %> |
<%= link_to 'Back', clogs_path %>

app/views/layouts/clogs/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clogs</title>
  <%= stylesheet_link_tag    "clogs/application", :media => "all" %>
  <%= javascript_include_tag "clogs/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>